- name: Install PostgreSQL
  ansible.builtin.package:
    name: postgresql
    state: present
- name: Install Git
  ansible.builtin.package:
    name: git
    state: present
- name: Create User
  ansible.builtin.user:
    name: myuser
    state: present

- name: Add Git Config
  ansible.builtin.copy:
    src: files/.gitconfig
    dest: /home/myuser/.gitconfig
    owner: myuser
    group: myuser