- hosts: servers
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80
    greeting: "This is server {{ server_name }}!"
    title: "{{ greeting | upper }}"
    date: "{{ ansible_facts['date_time']['date'] }}"
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
      become: yes

    - name: run cowsay
      ansible.builtin.command: cowsay "This is server {{ server_name }} !"
      register: cowsay_result

    

    - name: html nginx page
      ansible.builtin.template:
        src: files/index.html
        dest: "{{ root_dir }}/index.html"
      become: yes
    
    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes